Repository kryoniteorg/kryo-discord-whitelist, pull requests merged in 2022-01, with the labels that each got.

#8 Add velocity plugin to handle the Minecraft side of the whitelist
  bot/src/main/java/org/kryonite/kryodiscordwhitelist/bot/KryoDiscordWhitelistBot.java
  bot/src/main/java/org/kryonite/kryodiscordwhitelist/bot/listener/MessageListener.java
  bot/src/test/java/org/kryonite/kryodiscordwhitelist/bot/listener/MessageListenerTest.java
  build.gradle.kts
  common/build.gradle.kts
  common/src/main/java/org/kryonite/kryodiscordwhitelist/common/persistence/entity/User.java
  common/src/main/java/org/kryonite/kryodiscordwhitelist/common/persistence/repository/UserRepository.java
  common/src/main/java/org/kryonite/kryodiscordwhitelist/common/persistence/repository/impl/MariaDbUserRepository.java
  common/src/test/java/org/kryonite/kryodiscordwhitelist/common/persistence/repository/impl/MariaDbUserRepositoryTest.java
  velocity/build.gradle.kts
  velocity/src/main/java/org/kryonite/kryodiscordwhitelist/velocity/KryoDiscordWhitelistPlugin.java
  velocity/src/main/java/org/kryonite/kryodiscordwhitelist/velocity/listener/PlayerListener.java
  velocity/src/test/java/org/kryonite/kryodiscordwhitelist/velocity/KryoDiscordWhitelistPluginTest.java
  velocity/src/test/java/org/kryonite/kryodiscordwhitelist/velocity/listener/PlayerListenerTest.java
Labels: enhancement

#9 Add whitelist command
  bot/src/main/java/org/kryonite/kryodiscordwhitelist/bot/KryoDiscordWhitelistBot.java
  bot/src/test/java/org/kryonite/kryodiscordwhitelist/bot/KryoDiscordWhitelistBotTest.java
  common/src/main/java/org/kryonite/kryodiscordwhitelist/common/persistence/repository/UserRepository.java
  common/src/main/java/org/kryonite/kryodiscordwhitelist/common/persistence/repository/impl/MariaDbUserRepository.java
  common/src/test/java/org/kryonite/kryodiscordwhitelist/common/persistence/repository/impl/MariaDbUserRepositoryTest.java
  velocity/src/main/java/org/kryonite/kryodiscordwhitelist/velocity/KryoDiscordWhitelistPlugin.java
  velocity/src/main/java/org/kryonite/kryodiscordwhitelist/velocity/command/WhitelistCommand.java
  velocity/src/test/java/org/kryonite/kryodiscordwhitelist/velocity/KryoDiscordWhitelistPluginTest.java
  velocity/src/test/java/org/kryonite/kryodiscordwhitelist/velocity/command/WhitelistCommandTest.java
Labels: enhancement

#12 feat: Add multi proxy support
  lombok.config
  velocity/build.gradle.kts
  velocity/src/main/java/org/kryonite/kryodiscordwhitelist/velocity/KryoDiscordWhitelistPlugin.java
  velocity/src/main/java/org/kryonite/kryodiscordwhitelist/velocity/command/WhitelistCommand.java
  velocity/src/main/java/org/kryonite/kryodiscordwhitelist/velocity/messaging/MessagingController.java
  velocity/src/main/java/org/kryonite/kryodiscordwhitelist/velocity/messaging/consumer/PlayerRemovedFromWhitelistConsumer.java
  velocity/src/main/java/org/kryonite/kryodiscordwhitelist/velocity/messaging/message/PlayerRemovedFromWhitelist.java
  velocity/src/test/java/org/kryonite/kryodiscordwhitelist/velocity/KryoDiscordWhitelistPluginTest.java
  velocity/src/test/java/org/kryonite/kryodiscordwhitelist/velocity/command/WhitelistCommandTest.java
  velocity/src/test/java/org/kryonite/kryodiscordwhitelist/velocity/messaging/MessagingControllerTest.java
  velocity/src/test/java/org/kryonite/kryodiscordwhitelist/velocity/messaging/consumer/PlayerRemovedFromWhitelistConsumerTest.java
Labels: enhancement

#14 feat: Add release drafter and label sync
  .github/release-drafter.yml
  .github/workflows/label-sync.yaml
  .github/workflows/release-drafter.yaml
Labels: enhancement

#15 bugfix: Use Hikari for connection management
  bot/src/main/java/org/kryonite/kryodiscordwhitelist/bot/KryoDiscordWhitelistBot.java
  bot/src/main/java/org/kryonite/kryodiscordwhitelist/bot/listener/MessageListener.java
  bot/src/test/java/org/kryonite/kryodiscordwhitelist/bot/KryoDiscordWhitelistBotTest.java
  bot/src/test/java/org/kryonite/kryodiscordwhitelist/bot/listener/MessageListenerTest.java
  common/build.gradle.kts
  common/src/main/java/org/kryonite/kryodiscordwhitelist/common/persistence/repository/impl/MariaDbUserRepository.java
  common/src/test/java/org/kryonite/kryodiscordwhitelist/common/persistence/repository/impl/MariaDbUserRepositoryTest.java
  velocity/src/main/java/org/kryonite/kryodiscordwhitelist/velocity/KryoDiscordWhitelistPlugin.java
  velocity/src/test/java/org/kryonite/kryodiscordwhitelist/velocity/KryoDiscordWhitelistPluginTest.java
Labels: bugfix

#16 fix: Rename to KryoniteOrg to fit domain
  .github/workflows/label-sync.yaml
  .github/workflows/main.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/wrapper-validation.yaml
  build.gradle.kts
  velocity/build.gradle.kts
Labels: bugfix

#19 fix: Multiple small issues
  bot/src/main/java/org/kryonite/kryodiscordwhitelist/bot/listener/MessageListener.java
  bot/src/test/java/org/kryonite/kryodiscordwhitelist/bot/listener/MessageListenerTest.java
  common/src/main/java/org/kryonite/kryodiscordwhitelist/common/persistence/repository/impl/MariaDbUserRepository.java
Labels: bugfix

#21 Bugfix: Fix a possible SQL connection timeout
  common/src/main/java/org/kryonite/kryodiscordwhitelist/common/persistence/repository/impl/MariaDbUserRepository.java
Labels: bugfix

#22 feat: Whitelist command tab completion
  velocity/src/main/java/org/kryonite/kryodiscordwhitelist/velocity/KryoDiscordWhitelistPlugin.java
  velocity/src/main/java/org/kryonite/kryodiscordwhitelist/velocity/command/WhitelistCommand.java
  velocity/src/test/java/org/kryonite/kryodiscordwhitelist/velocity/command/WhitelistCommandTest.java
Labels: feature

#27 fix: Change sonarcloud key to new project name
  build.gradle.kts
Labels: bugfix

#29 fix: Add more tests
  velocity/src/test/java/org/kryonite/kryodiscordwhitelist/velocity/command/WhitelistCommandTest.java
Labels: bugfix

#28 feat: Add README file
  README.md
Labels: feature

#33 feat: Increment version to 1.0.0
  build.gradle.kts
  velocity/src/main/java/org/kryonite/kryodiscordwhitelist/velocity/KryoDiscordWhitelistPlugin.java
Labels: feature

#34 feat: Rename Hikari connection pool
  bot/src/main/java/org/kryonite/kryodiscordwhitelist/bot/KryoDiscordWhitelistBot.java
  velocity/src/main/java/org/kryonite/kryodiscordwhitelist/velocity/KryoDiscordWhitelistPlugin.java
Labels: feature

#38 fix: Change queue name from UUID to servername
  velocity/src/main/java/org/kryonite/kryodiscordwhitelist/velocity/KryoDiscordWhitelistPlugin.java
  velocity/src/main/java/org/kryonite/kryodiscordwhitelist/velocity/messaging/MessagingController.java
Labels: bugfix

#37 fix: Fix identation of Jar task
  bot/build.gradle.kts
  bot/src/main/java/org/kryonite/kryodiscordwhitelist/bot/KryoDiscordWhitelistBot.java
  build.gradle.kts
Labels: enhancement, bugfix
